# pod.yaml
# 
---
apiVersion: v1   
kind: Pod        
metadata:        
  name: web
  labels:
    app: web
spec:                
  containers:        
  - name: frontend   
    image: nginx     
    ports:
    - containerPort: 80
