let a = {
  msg: "ok",
  code: 200,
  data: {
    0: {
      scheduleCount: 0,
      otherSourceCount: 3,
      postCount: 2,
      authorCount: 1,
      postNews: [
        {
          newsId: 6157002,
          newsTitle: "不僅尺碼稱霸，Land Rover Defender 130 X P400 更於功能與豪華面向攻頂",
          newsDate: "2023-06-01 00:25:01",
          pushAuthor: "有車賞",
          otherSource: false,
        },
        {
          newsId: 6156998,
          newsTitle: " 這才是真正鴨王，Powertune Australia操刀 Toyota GR Yaris馬力暴增至740匹 ",
          newsDate: "2023-06-01 00:25:20",
          pushAuthor: "車勢文化",
          otherSource: false,
        },
        {
          newsId: 6157000,
          newsTitle: " 大鼻孔要掰掰了，BMW設計師透露水箱護罩尺寸將變動 ",
          newsDate: "2023-06-01 00:25:20",
          pushAuthor: "車勢文化",
          otherSource: false,
        },
        {
          newsId: 6157004,
          newsTitle: "民進黨爆性騷　前黨工控主管「高舉婦權旗幟未成為我的翁文方」",
          newsDate: "2023-06-01 00:31:57",
          pushAuthor: "陳威叡",
          otherSource: false,
        },
        {
          newsId: 6157007,
          newsTitle: "前黨工指控被性騷主管冷處理　民進黨致歉承諾調查、懲處",
          newsDate: "2023-06-01 00:45:22",
          pushAuthor: "陳威叡",
          otherSource: false,
        },
      ],
    },
    1: {
      scheduleCount: 0,
      otherSourceCount: 1,
      postCount: 0,
      authorCount: 0,
      postNews: [
        {
          newsId: 6157008,
          newsTitle: "承襲 XFC Concept 概念車設計 Mitsubishi 預告全新休旅車款將在印尼登場",
          newsDate: "2023-06-01 01:25:40",
          pushAuthor: "小七車觀點",
          otherSource: false,
        },
      ],
    },
    2: {
      scheduleCount: 0,
      otherSourceCount: 1,
      postCount: 0,
      authorCount: 0,
      postNews: [
        {
          newsId: 6157010,
          newsTitle: "承襲北歐極簡主計風格 Volvo EX30 內裝設計首度公開",
          newsDate: "2023-06-01 02:55:40",
          pushAuthor: "小七車觀點",
          otherSource: false,
        },
      ],
    },
    3: {
      scheduleCount: 0,
      otherSourceCount: 0,
      postCount: 0,
      authorCount: 0,
      postNews: [],
    },
    4: {
      scheduleCount: 0,
      otherSourceCount: 0,
      postCount: 0,
      authorCount: 0,
      postNews: [],
    },
    5: {
      scheduleCount: 0,
      otherSourceCount: 2,
      postCount: 0,
      authorCount: 0,
      postNews: [
        {
          newsId: 6156889,
          newsTitle: "美國主導海上部隊保護波灣水道安全　阿聯停止參與",
          newsDate: "2023-06-01 05:00:00",
          pushAuthor: "中央社",
          otherSource: false,
        },
        {
          newsId: 6156871,
          newsTitle: "「我們渴望自由」！菲律賓人要求離婚合法化",
          newsDate: "2023-06-01 05:56:28",
          pushAuthor: "中央社",
          otherSource: false,
        },
      ],
    },
    6: {
      scheduleCount: 0,
      otherSourceCount: 5,
      postCount: 3,
      authorCount: 3,
      postNews: [
        {
          newsId: 6156236,
          newsTitle: "1戶3萬元房貸補貼今早上線！申請4步驟公開　網址、入帳日懶人包",
          newsDate: "2023-06-01 06:00:00",
          pushAuthor: "徐銘穗",
          otherSource: false,
        },
        {
          newsId: 6156885,
          newsTitle: "印度矽谷開發過速　報告估需104億元投入防洪",
          newsDate: "2023-06-01 06:00:32",
          pushAuthor: "中央社",
          otherSource: false,
        },
        {
          newsId: 6156911,
          newsTitle: "歐洲離岸風場安全亮紅燈　能源自主願景面臨挑戰",
          newsDate: "2023-06-01 06:03:51",
          pushAuthor: "中央社",
          otherSource: false,
        },
        {
          newsId: 6156929,
          newsTitle: "布林肯指責共機攔截美機行動　仍盼雙方建立溝通管道",
          newsDate: "2023-06-01 06:05:27",
          pushAuthor: "中央社",
          otherSource: false,
        },
        {
          newsId: 6157011,
          newsTitle: "英國也傳名人廣告詐騙案　馬斯克及貝佐斯肖像遭冒用",
          newsDate: "2023-06-01 06:07:26",
          pushAuthor: "中央社",
          otherSource: false,
        },
        {
          newsId: 6157015,
          newsTitle: "川普昔日副手變對手　美前副總統彭斯傳下週宣布問鼎白宮",
          newsDate: "2023-06-01 06:09:13",
          pushAuthor: "中央社",
          otherSource: false,
        },
        {
          newsId: 6156870,
          newsTitle: "一刷牙就流血害怕到不行？「4種原因」曝光　醫師：還是不能不刷",
          newsDate: "2023-06-01 06:15:00",
          pushAuthor: "潘毅",
          otherSource: false,
        },
        {
          newsId: 6157027,
          newsTitle: "烏克蘭最後的戰艦遭毀？烏海軍司令：我們打掉俄國18艘",
          newsDate: "2023-06-01 06:46:33",
          pushAuthor: "蔡姍伶",
          otherSource: false,
        },
      ],
    },
    7: {
      scheduleCount: 0,
      otherSourceCount: 0,
      postCount: 7,
      authorCount: 7,
      postNews: [
        {
          newsId: 6156814,
          newsTitle: "華航「機微酒」打造奢華旅遊　再推陽明春天「米其林素食」飛機餐",
          newsDate: "2023-06-01 07:00:00",
          pushAuthor: "蕭涵云",
          otherSource: false,
        },
        {
          newsId: 6156634,
          newsTitle: "6月星座運勢公開！3星座厄運纏身　第1名要注意感情債",
          newsDate: "2023-06-01 07:07:00",
          pushAuthor: "徐銘穗",
          otherSource: false,
        },
        {
          newsId: 6156775,
          newsTitle: "黃仁勳 AI最強業務員！口中的「生成式AI」是什麼？4點解惑",
          newsDate: "2023-06-01 07:15:00",
          pushAuthor: "周淑萍",
          otherSource: false,
        },
        {
          newsId: 6157030,
          newsTitle: "六四將迎34周年！傳北京「四通橋」路牌遭拆",
          newsDate: "2023-06-01 07:24:20",
          pushAuthor: "蔡姍伶",
          otherSource: false,
        },
        {
          newsId: 6157033,
          newsTitle: "只有今天！7-11精品美式、拿鐵「買7送7」　特大美式23元開喝",
          newsDate: "2023-06-01 07:37:52",
          pushAuthor: "鍾怡婷",
          otherSource: false,
        },
        {
          newsId: 6157034,
          newsTitle: "網球／台女將捷報！詹家姐妹法網首輪逆轉晉級　吳芳嫺也闖進32強",
          newsDate: "2023-06-01 07:52:17",
          pushAuthor: "黃建霖",
          otherSource: false,
        },
        {
          newsId: 6157035,
          newsTitle: "台南深夜氣爆！中央廚房雜物炸飛到馬路　1人遭天花板砸中送醫",
          newsDate: "2023-06-01 07:58:31",
          pushAuthor: "陳苾暐",
          otherSource: false,
        },
      ],
    },
    8: {
      scheduleCount: 0,
      otherSourceCount: 0,
      postCount: 12,
      authorCount: 10,
      postNews: [
        {
          newsId: 6156908,
          newsTitle: "瑪娃颱風依依不捨！「5縣市」大雨特報　一路下到明天才趨緩",
          newsDate: "2023-06-01 08:01:52",
          pushAuthor: "張志浩",
          otherSource: false,
        },
        {
          newsId: 6156645,
          newsTitle: "雲林銀髮人才服務據點助銀髮族重返職場",
          newsDate: "2023-06-01 08:05:00",
          pushAuthor: "林怡孜",
          otherSource: false,
        },
        {
          newsId: 6156732,
          newsTitle: "華航聯名燈燈庵！飛機餐吃懷石料理　「甜點界的香奈兒」也飛上天",
          newsDate: "2023-06-01 08:05:00",
          pushAuthor: "蕭涵云",
          otherSource: false,
        },
        {
          newsId: 6157040,
          newsTitle: "NBA總冠軍賽／熱火英雄哥Herro將缺席G1　美媒透露預計回歸時間點",
          newsDate: "2023-06-01 08:10:13",
          pushAuthor: "黃建霖",
          otherSource: false,
        },
        {
          newsId: 6157041,
          newsTitle: "83歲《教父》艾爾帕西諾又當爸！小女友將臨盆　孩子成年他當人瑞",
          newsDate: "2023-06-01 08:12:15",
          pushAuthor: "楊穎軒",
          otherSource: false,
        },
        {
          newsId: 6156692,
          newsTitle: "官方版高薪職業調查曝光　冠軍職業全台有3065人！年薪破400萬元",
          newsDate: "2023-06-01 08:14:00",
          pushAuthor: "徐銘穗",
          otherSource: false,
        },
        {
          newsId: 6157044,
          newsTitle: "黃仁勳將赴中國！彭博：拜訪騰訊、字節跳動及電動車商",
          newsDate: "2023-06-01 08:20:35",
          pushAuthor: "蔡姍伶",
          otherSource: false,
        },
        {
          newsId: 6157045,
          newsTitle: "台東市火鍋店深夜惡火！恐怖黑濃煙竄天　老闆娘獲救無心跳搶救中",
          newsDate: "2023-06-01 08:25:35",
          pushAuthor: "陳苾暐",
          otherSource: false,
        },
        {
          newsId: 6157046,
          newsTitle: "房市／台南年輕人愛買「透天厝」？專家揭關鍵：長輩出錢",
          newsDate: "2023-06-01 08:26:56",
          pushAuthor: "黃韻文",
          otherSource: false,
        },
        {
          newsId: 6157057,
          newsTitle: "NBA季後賽／塞爾提克主帥形同虛設？名球評：搶七是Horford在執教",
          newsDate: "2023-06-01 08:36:42",
          pushAuthor: "黃建霖",
          otherSource: false,
        },
        {
          newsId: 6157060,
          newsTitle: "MLB／大谷翔平太猛了！單場雙轟4打點！助天使12:5大勝白襪",
          newsDate: "2023-06-01 08:43:39",
          pushAuthor: "吳政紘",
          otherSource: false,
        },
        {
          newsId: 6157047,
          newsTitle: "房市／讀者文摘信譽品牌揭曉　指標企業同獲獎",
          newsDate: "2023-06-01 08:45:00",
          pushAuthor: "黃韻文",
          otherSource: false,
        },
      ],
    },
    9: {
      scheduleCount: 0,
      otherSourceCount: 6,
      postCount: 18,
      authorCount: 11,
      postNews: [
        {
          newsId: 6156736,
          newsTitle: "一兆元男人4／輝達財測看端倪　黃仁勳「大秀肌肉」讓AI股爆紅",
          newsDate: "2023-06-01 09:00:00",
          pushAuthor: "許家禎",
          otherSource: false,
        },
        {
          newsId: 6156773,
          newsTitle: "一兆元男人2／黃仁勳、張忠謀因一封email相識　小故事全畫成漫畫",
          newsDate: "2023-06-01 09:00:00",
          pushAuthor: "許家禎",
          otherSource: false,
        },
        {
          newsId: 6156776,
          newsTitle: "一兆元男人3／黃仁勳超級親民　「愛穿皮衣」背後原因好單純",
          newsDate: "2023-06-01 09:00:00",
          pushAuthor: "許家禎",
          otherSource: false,
        },
        {
          newsId: 6156780,
          newsTitle: "一兆元男人1／GPU熬30年走上神壇地位　黃仁勳成「新時代巨人」",
          newsDate: "2023-06-01 09:00:00",
          pushAuthor: "鄭妤安",
          otherSource: false,
        },
        {
          newsId: 6156866,
          newsTitle: "一兆元男人5／輝達成功難以複製　科技專家：台灣AI突破點在這",
          newsDate: "2023-06-01 09:00:00",
          pushAuthor: "鄭妤安",
          otherSource: false,
        },
        {
          newsId: 6156997,
          newsTitle: "雨季來了！中國駐泰使館發布公告　提醒遊客小心安全",
          newsDate: "2023-06-01 09:00:00",
          pushAuthor: "詹凌瑀",
          otherSource: false,
        },
        {
          newsId: 6157065,
          newsTitle: "新竹尖石鄉驚傳自撞！賓士車頭全毀竄火舌　23歲男送醫不治",
          newsDate: "2023-06-01 09:11:04",
          pushAuthor: "陳苾暐",
          otherSource: false,
        },
        {
          newsId: 6157069,
          newsTitle: "MLB／大谷翔平轟不停！自爆：「連界外球也看得很清楚！」",
          newsDate: "2023-06-01 09:13:50",
          pushAuthor: "吳政紘",
          otherSource: false,
        },
        {
          newsId: 6157070,
          newsTitle: "全球最大盜版影片網站RARBG關閉！網友集體崩潰：以後去哪裡下載",
          newsDate: "2023-06-01 09:17:20",
          pushAuthor: "楊穎軒",
          otherSource: false,
        },
        {
          newsId: 6157054,
          newsTitle: "房市／貫徹經營理念　信義房屋再獲消費者肯定",
          newsDate: "2023-06-01 09:20:00",
          pushAuthor: "黃韻文",
          otherSource: false,
        },
        {
          newsId: 6157072,
          newsTitle: "全車好料集一身 Land Rover Range Rover SV EDITION ONE 登場",
          newsDate: "2023-06-01 09:25:40",
          pushAuthor: "小七車觀點",
          otherSource: false,
        },
        {
          newsId: 6157075,
          newsTitle: "不想當美中夾心餅乾！路透：中國科企熱衷於「去中國化」",
          newsDate: "2023-06-01 09:26:53",
          pushAuthor: "蔡姍伶",
          otherSource: false,
        },
        {
          newsId: 6157077,
          newsTitle: "台股早盤一度跌百點　裕隆領軍！電動車零組件逆勢抗跌",
          newsDate: "2023-06-01 09:27:43",
          pushAuthor: "許家禎",
          otherSource: false,
        },
        {
          newsId: 6157078,
          newsTitle: "陸軍鑑測驚傳意外！44歲中校跳繩突休克　送醫裝設葉克膜搶救中",
          newsDate: "2023-06-01 09:28:12",
          pushAuthor: "陳苾暐",
          otherSource: false,
        },
        {
          newsId: 6157079,
          newsTitle: "侯友宜競選工作室成立！首波發言人團亮相　七八年級生為主力",
          newsDate: "2023-06-01 09:28:25",
          pushAuthor: "余祥",
          otherSource: false,
        },
        {
          newsId: 6157073,
          newsTitle: "術後出現幻覺？　當心是缺乏「這1種」維生素",
          newsDate: "2023-06-01 09:31:00",
          pushAuthor: "健康醫療網",
          otherSource: false,
        },
        {
          newsId: 6157076,
          newsTitle: "美聯準會官員喊話暫停升息　新台幣早盤止貶回升",
          newsDate: "2023-06-01 09:33:08",
          pushAuthor: "顏真真",
          otherSource: false,
        },
        {
          newsId: 6157099,
          newsTitle: "美國眾議院通過債務上限法案！將送參議院表決",
          newsDate: "2023-06-01 09:41:01",
          pushAuthor: "蔡姍伶",
          otherSource: false,
        },
        {
          newsId: 6157022,
          newsTitle: "英相蘇納克赴歐洲政治共同體峰會　主打安全議題",
          newsDate: "2023-06-01 09:42:19",
          pushAuthor: "中央社",
          otherSource: false,
        },
        {
          newsId: 6157031,
          newsTitle: "紐時：俄羅斯船隻暗地運油至中國　疑違反制裁",
          newsDate: "2023-06-01 09:44:57",
          pushAuthor: "中央社",
          otherSource: false,
        },
        {
          newsId: 6157080,
          newsTitle: "綠前黨工遭性騷被吃案　顏若芳：性騷零容忍、黨中央要嚴懲",
          newsDate: "2023-06-01 09:45:35",
          pushAuthor: "呂炯昌",
          otherSource: false,
        },
        {
          newsId: 6157039,
          newsTitle: "美跨黨派眾議員提決議案　籲台美洽簽租稅協定",
          newsDate: "2023-06-01 09:46:48",
          pushAuthor: "中央社",
          otherSource: false,
        },
        {
          newsId: 6157061,
          newsTitle: "馬杜洛訪巴西　委內瑞拉債務違約掀議論",
          newsDate: "2023-06-01 09:49:25",
          pushAuthor: "中央社",
          otherSource: false,
        },
        {
          newsId: 6157104,
          newsTitle: "掃黑打詐！黃明昭視導基隆警局肯定成效　頒發重大刑案慰勉金",
          newsDate: "2023-06-01 09:57:01",
          pushAuthor: "陳苾暐",
          otherSource: false,
        },
      ],
    },
    10: {
      scheduleCount: 0,
      otherSourceCount: 2,
      postCount: 4,
      authorCount: 4,
      postNews: [
        {
          newsId: 6157066,
          newsTitle: "水庫大進補！全台「累積雨量排行」出爐　翡翠、石門喝飽飽",
          newsDate: "2023-06-01 10:00:00",
          pushAuthor: "張志浩",
          otherSource: false,
        },
        {
          newsId: 6156026,
          newsTitle: "定食8今起「白飯、味增湯」免費吃到飽！炸物全8折　可爾必思18元",
          newsDate: "2023-06-01 10:01:46",
          pushAuthor: "蕭涵云",
          otherSource: false,
        },
        {
          newsId: 6157009,
          newsTitle: "就要台式粽！欣葉鹹粽「每年賣破10萬顆」　新天地開賣限量虎掌粽",
          newsDate: "2023-06-01 10:03:16",
          pushAuthor: "葉盛耀",
          otherSource: false,
        },
        {
          newsId: 6157110,
          newsTitle: "MLB／大谷翔平轉戰洋基？美媒爆邪惡帝國將出手搶人",
          newsDate: "2023-06-01 10:03:39",
          pushAuthor: "吳政紘",
          otherSource: false,
        },
        {
          newsId: 9069032,
          newsTitle: "地震速報",
          newsDate: "2023-06-01 10:41:31",
          pushAuthor: "中央氣象局",
          otherSource: false,
        },
        {
          newsId: 9069037,
          newsTitle: "地震速報",
          newsDate: "2023-06-01 10:56:37",
          pushAuthor: "中央氣象局",
          otherSource: false,
        },
      ],
    },
    11: {
      scheduleCount: 0,
      otherSourceCount: 0,
      postCount: 0,
      authorCount: 0,
      postNews: [],
    },
    12: {
      scheduleCount: 0,
      otherSourceCount: 0,
      postCount: 0,
      authorCount: 0,
      postNews: [],
    },
    13: {
      scheduleCount: 0,
      otherSourceCount: 0,
      postCount: 0,
      authorCount: 0,
      postNews: [],
    },
    14: {
      scheduleCount: 0,
      otherSourceCount: 0,
      postCount: 0,
      authorCount: 0,
      postNews: [],
    },
    15: {
      scheduleCount: 0,
      otherSourceCount: 0,
      postCount: 0,
      authorCount: 0,
      postNews: [],
    },
    16: {
      scheduleCount: 0,
      otherSourceCount: 0,
      postCount: 0,
      authorCount: 0,
      postNews: [],
    },
    17: {
      scheduleCount: 0,
      otherSourceCount: 0,
      postCount: 0,
      authorCount: 0,
      postNews: [],
    },
    18: {
      scheduleCount: 0,
      otherSourceCount: 0,
      postCount: 0,
      authorCount: 0,
      postNews: [],
    },
    19: {
      scheduleCount: 0,
      otherSourceCount: 0,
      postCount: 0,
      authorCount: 0,
      postNews: [],
    },
    20: {
      scheduleCount: 0,
      otherSourceCount: 0,
      postCount: 0,
      authorCount: 0,
      postNews: [],
    },
    21: {
      scheduleCount: 0,
      otherSourceCount: 0,
      postCount: 0,
      authorCount: 0,
      postNews: [],
    },
    22: {
      scheduleCount: 0,
      otherSourceCount: 0,
      postCount: 0,
      authorCount: 0,
      postNews: [],
    },
    23: {
      scheduleCount: 0,
      otherSourceCount: 0,
      postCount: 0,
      authorCount: 0,
      postNews: [],
    },
  },
};

console.log(a.data[0].postNews.filter((item) => item.otherSource === false).length);

for (const key in a.data) {
  // console.log(a.data[key].postNews.length);
  let b = a.data[key].postNews.filter((item) => item.otherSource === false).length;
  console.log(b);
}
