apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-3000
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: blue.linx.website
    http:
      paths:
      - path: /blue
        pathType: Prefix  
        backend:
          service:
            name: blue-service
            port:
              number: 3000
  - host: purple.linx.website
    http:
      paths:
      - path: /purple
        pathType: Prefix
        backend:
          service:
            name: purple-service
            port:
              number: 3000