sudo userdel -r kano4236
sudo userdel -r kanowu
sudo userdel -r austinchen
sudo userdel -r johnsonchuang
sudo userdel -r sandychien
sudo userdel -r research_development
sudo userdel -r SOHO-Min
sudo userdel -r soho-mikechen
sudo userdel -r sunnytsay
sudo userdel -r lin
sudo userdel -r linx9581
sudo userdel -r nownews
sudo userdel -r stg
sudo userdel -r yuskawu_work
sudo userdel -r nnbkman
sudo userdel -r genlin520
sudo userdel -r ctimatt
sudo userdel -r zabbix
sudo userdel -r thesys-ken
sudo userdel -r thesys-emma
sudo userdel -r kenyang65
sudo userdel -r linx
sudo userdel -r gcp
sudo userdel -r alex_lion
sudo userdel -r erinhsieh
sudo userdel -r nn-austinchen
sudo userdel -r nnaustin
sudo userdel -r brianchang_nownews
sudo userdel -r franktseng_nownews