{
 "title": "pm2",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "name", "query": "label_values(pm2_up, name)" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "pm2_uptime{name=\"$name\"}"
    }
   ]
  },
  {
   "title": "pm2 up",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(pm2_up{name=\"$name\"} == 1)",
     "legendFormat": "pm2 up"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "pm2_instances{name=\"$name\"}"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pm2_instances{name=\"$name\"}",
     "legendFormat": "instances"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pm2_cpu{name=\"$name\"}",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "pm2_memory{name=\"$name\"}",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Restarts per minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pm2_restarts{name=\"$name\"}[1m])",
     "legendFormat": "restarts"
    }
   ]
  },
  {
   "title": "Active handles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pm2_active_handles{name=\"$name\"}",
     "legendFormat": "active handles"
    }
   ]
  },
  {
   "title": "HTTP Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "pm2_http_mean_latency{name=\"$name\"}",
     "legendFormat": "mean"
    },
    {
     "expr": "pm2_http_p95_latency{name=\"$name\"}",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Event Loop Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "pm2_event_loop_latency{name=\"$name\"}",
     "legendFormat": "mean"
    },
    {
     "expr": "pm2_event_loop_latency_p95{name=\"$name\"}",
     "legendFormat": "p95"
    }
   ]
  }
 ]
}