---
- name: Copy and Run shell scripts on remote machine
  vars_prompt:
    - name: host
      prompt: What is your host?
      private: no
      
  hosts: '{{ host }}'
  tasks:
    - name: upload
      synchronize:
        mode: push
        dest: /home/ansible
        src: ../../deploy/monit/exporter

    - name: run exporter-local.sh
      shell: "sudo sh /home/ansible/exporter/exporter-local.sh"

    - name: rm exporter-local.sh
      shell: "sudo rm /home/ansible/exporter/*.sh"