filebeat.inputs:
- type: log
  enabled: true
  backoff: "1s"            # 一秒掃一次
  tail_files: true         # 預設是false 會從log最後一行開始記錄
  paths:
    - /root/.pm2/logs/*-error.log
  exclude_files: ['\.gz$']
  fields:                   # 這邊設的變數可以從logstash的output中取得 [fields][log_topics]
    log_topics: log_nginx_access
  fields_under_root: true   # 這邊設置true output那邊就不用加[fields]
  include_lines: ['keyword1', 'keyword2', 'keyword3'] # 可以用來過濾log符合這些字串才傳

output.logstash:
  hosts: ["localhost:5044"]
