FROM tomcat:9-jdk8-openjdk

# 複製WAR檔案到Tomcat的webapps目錄
COPY ./test.war /usr/local/tomcat/webapps/

# 複製自定義的server.xml到Tomcat的conf目錄
COPY ./server.xml /usr/local/tomcat/conf/

# 複製setenv.sh到Tomcat的bin目錄
COPY ./setenv.sh /usr/local/tomcat/bin/

# 確保setenv.sh具有執行權限
RUN chmod +x /usr/local/tomcat/bin/setenv.sh

# 暴露80端口
EXPOSE 80

# 啟動Tomcat
CMD ["catalina.sh", "run"]