global: 
  resolve_timeout: 5m
route:
  receiver: critical
  group_interval: 5s
  repeat_interval: 1m
  routes:
  - match:
      severity: critical
    receiver: critical
receivers:
- name: 'critical'
  webhook_configs:
  - url: 'http://127.0.0.1:3500/alert'
    send_resolved: true