global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
- "/etc/prometheus/rules.yml"

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - 10.140.0.26:9093
  
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['10.140.0.26:9090']
  - job_name: 'host1'
    static_configs:
      - targets: ['10.140.0.26:9100']
