apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: helloworld-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: hello-deployment
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 10