
filebeat.inputs:
- type: filestream
  enabled: true
  backoff: "1s"             # 一秒掃一次
  tail_files: false         # 預設是false 會從log最後一行開始記錄
  paths:
    - /var/log/nginx/access.log
  exclude_files: ['\.gz$']
  fields:                   # 這邊設的變數可以從logstash的output中取得 [fields][log_topics]
    log_topics: log_nginx_access1
  fields_under_root: true   # 這邊設置true output那邊就不用加[fields]

output.logstash:
  hosts: ["35.221.153.255:5044"]
filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1