---
- name: show env
  hosts: '{{ host }}'
  tasks:
    - name: upload
      synchronize:
        mode: push
        dest: /home/ansible
        src: ../../deploy

    - name: delete_user
      shell: "sudo sh /home/ansible/deploy/env/shell/delete_user.sh"
      register: env

    - name: show home
      shell: "more /etc/passwd"
      register: env

    - name: Print
      debug:
        msg: "{{ env.stdout.split('\n') }}"
