---
- name: show env
  hosts: '{{ host }}'
  tasks:
    # - name: show env
    #   shell: "grep 'export' /etc/profile"
    #   register: env

    # - name: show logs
    #   shell: "sudo ls -l /opt/tomcat/logs"
    #   register: env

    - name: show system infos
      shell: "sudo uname -a"
      register: env

    - name: Print
      debug:
        msg: "{{ env.stdout.split('\n') }}"



    # - name: show system info
    #   shell: "lsb_release -a"
    #   register: env

    # - name: Extract description
    #   set_fact:
    #     description: "{{ (env.stdout_lines | select('search', 'Description') | list | first).split(':') | last | trim }}"

    # - name: Print
    #   debug:
    #     msg: "{{ description }}"