---
- name: Copy and Run shell scripts on remote machine
  vars_prompt:
    - name: host
      prompt: What is your host?
      private: no
      
  hosts: '{{ host }}'
  tasks:
    - name: "creating directory"
      file:
        state: directory
        path: /home/lin/ans
        owner: lin
        group: lin
        mode: 0755

    - name: upload shell scripts
      synchronize:
        mode: push
        dest: /home/lin/ans
        src: ./php.sh