---
- name: Copy and Run shell scripts on remote machine
  hosts: servers
  tasks:
    - name: "creating directory"
      file:
        state: directory
        path: /home/lin/ans
        owner: lin
        group: lin
        mode: 0755

    - name: upload shell scripts
      synchronize:
        mode: push
        dest: /home/lin/ans
        src: ./php.sh

    - name: run php.sh
      shell: "sudo sh /home/lin/ans/php.sh"

    - name: read file content
      command: "cat /home/lin/ans/php.sh"
      register: out

    - name: Print the msg
      debug:
        msg: "{{ out.stdout }}"