---
- name: Copy and Run shell scripts on remote machine
  vars_prompt:
    - name: host
      prompt: What is your host?
      private: no
      
  hosts: '{{ host }}'
  tasks:
    - name: run php.sh
      shell: "sudo sh /home/ansible/devops/shell/php.sh"
      register: sh