---
- name: Copy and Run shell scripts on remote machine
  hosts: "{{ host }}"
  vars:
    ansible_ssh_private_key_file: /home/gitlab-runner/.ssh/id_rsa
  tasks:
    - name: show tcp_fin_timeout
      shell: "sudo sysctl -a | grep tcp_fin_timeout"
      register: tcp_fin_timeout

    - name: show tcp_tw_reuse
      shell: "sudo sysctl -a | grep tcp_tw_reuse"
      register: tcp_tw_reuse

    - name: show tcp_count
      shell: "sudo netstat -ant | wc -l"
      register: tcp_count

    - name: Print
      debug:
        msg: "'{{ tcp_fin_timeout.stdout }}' '{{ tcp_tw_reuse.stdout }}' 'tcp連線數:{{ tcp_count.stdout }}'"